// Code generated by protoc-gen-go. DO NOT EDIT.
// source: whatnot.proto

package transports

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type EventType int32

const (
	EventType_LEASE   EventType = 0
	EventType_LOCK    EventType = 1
	EventType_RELEASE EventType = 2
	EventType_CREATE  EventType = 3
	EventType_DELETE  EventType = 4
)

var EventType_name = map[int32]string{
	0: "LEASE",
	1: "LOCK",
	2: "RELEASE",
	3: "CREATE",
	4: "DELETE",
}

var EventType_value = map[string]int32{
	"LEASE":   0,
	"LOCK":    1,
	"RELEASE": 2,
	"CREATE":  3,
	"DELETE":  4,
}

func (x EventType) String() string {
	return proto.EnumName(EventType_name, int32(x))
}

func (EventType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_7e1fe3d4eec11dd6, []int{0}
}

type LeaseRequest struct {
	AbsolutePath         string   `protobuf:"bytes,1,opt,name=AbsolutePath,proto3" json:"AbsolutePath,omitempty"`
	Duration             int64    `protobuf:"varint,2,opt,name=Duration,proto3" json:"Duration,omitempty"`
	Prefix               bool     `protobuf:"varint,3,opt,name=Prefix,proto3" json:"Prefix,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LeaseRequest) Reset()         { *m = LeaseRequest{} }
func (m *LeaseRequest) String() string { return proto.CompactTextString(m) }
func (*LeaseRequest) ProtoMessage()    {}
func (*LeaseRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7e1fe3d4eec11dd6, []int{0}
}

func (m *LeaseRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LeaseRequest.Unmarshal(m, b)
}
func (m *LeaseRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LeaseRequest.Marshal(b, m, deterministic)
}
func (m *LeaseRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LeaseRequest.Merge(m, src)
}
func (m *LeaseRequest) XXX_Size() int {
	return xxx_messageInfo_LeaseRequest.Size(m)
}
func (m *LeaseRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LeaseRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LeaseRequest proto.InternalMessageInfo

func (m *LeaseRequest) GetAbsolutePath() string {
	if m != nil {
		return m.AbsolutePath
	}
	return ""
}

func (m *LeaseRequest) GetDuration() int64 {
	if m != nil {
		return m.Duration
	}
	return 0
}

func (m *LeaseRequest) GetPrefix() bool {
	if m != nil {
		return m.Prefix
	}
	return false
}

type LeaseResponse struct {
	AbsolutePath         string   `protobuf:"bytes,1,opt,name=AbsolutePath,proto3" json:"AbsolutePath,omitempty"`
	Duration             int64    `protobuf:"varint,2,opt,name=Duration,proto3" json:"Duration,omitempty"`
	LeaseId              int64    `protobuf:"varint,3,opt,name=LeaseId,proto3" json:"LeaseId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LeaseResponse) Reset()         { *m = LeaseResponse{} }
func (m *LeaseResponse) String() string { return proto.CompactTextString(m) }
func (*LeaseResponse) ProtoMessage()    {}
func (*LeaseResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7e1fe3d4eec11dd6, []int{1}
}

func (m *LeaseResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LeaseResponse.Unmarshal(m, b)
}
func (m *LeaseResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LeaseResponse.Marshal(b, m, deterministic)
}
func (m *LeaseResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LeaseResponse.Merge(m, src)
}
func (m *LeaseResponse) XXX_Size() int {
	return xxx_messageInfo_LeaseResponse.Size(m)
}
func (m *LeaseResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LeaseResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LeaseResponse proto.InternalMessageInfo

func (m *LeaseResponse) GetAbsolutePath() string {
	if m != nil {
		return m.AbsolutePath
	}
	return ""
}

func (m *LeaseResponse) GetDuration() int64 {
	if m != nil {
		return m.Duration
	}
	return 0
}

func (m *LeaseResponse) GetLeaseId() int64 {
	if m != nil {
		return m.LeaseId
	}
	return 0
}

type LeaseRelease struct {
	LeaseId              int64    `protobuf:"varint,1,opt,name=LeaseId,proto3" json:"LeaseId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LeaseRelease) Reset()         { *m = LeaseRelease{} }
func (m *LeaseRelease) String() string { return proto.CompactTextString(m) }
func (*LeaseRelease) ProtoMessage()    {}
func (*LeaseRelease) Descriptor() ([]byte, []int) {
	return fileDescriptor_7e1fe3d4eec11dd6, []int{2}
}

func (m *LeaseRelease) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LeaseRelease.Unmarshal(m, b)
}
func (m *LeaseRelease) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LeaseRelease.Marshal(b, m, deterministic)
}
func (m *LeaseRelease) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LeaseRelease.Merge(m, src)
}
func (m *LeaseRelease) XXX_Size() int {
	return xxx_messageInfo_LeaseRelease.Size(m)
}
func (m *LeaseRelease) XXX_DiscardUnknown() {
	xxx_messageInfo_LeaseRelease.DiscardUnknown(m)
}

var xxx_messageInfo_LeaseRelease proto.InternalMessageInfo

func (m *LeaseRelease) GetLeaseId() int64 {
	if m != nil {
		return m.LeaseId
	}
	return 0
}

type LeaseReleaseResponse struct {
	LeaseId              int64    `protobuf:"varint,1,opt,name=LeaseId,proto3" json:"LeaseId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LeaseReleaseResponse) Reset()         { *m = LeaseReleaseResponse{} }
func (m *LeaseReleaseResponse) String() string { return proto.CompactTextString(m) }
func (*LeaseReleaseResponse) ProtoMessage()    {}
func (*LeaseReleaseResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7e1fe3d4eec11dd6, []int{3}
}

func (m *LeaseReleaseResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LeaseReleaseResponse.Unmarshal(m, b)
}
func (m *LeaseReleaseResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LeaseReleaseResponse.Marshal(b, m, deterministic)
}
func (m *LeaseReleaseResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LeaseReleaseResponse.Merge(m, src)
}
func (m *LeaseReleaseResponse) XXX_Size() int {
	return xxx_messageInfo_LeaseReleaseResponse.Size(m)
}
func (m *LeaseReleaseResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LeaseReleaseResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LeaseReleaseResponse proto.InternalMessageInfo

func (m *LeaseReleaseResponse) GetLeaseId() int64 {
	if m != nil {
		return m.LeaseId
	}
	return 0
}

type LockRequest struct {
	AbsolutePath         string   `protobuf:"bytes,1,opt,name=AbsolutePath,proto3" json:"AbsolutePath,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LockRequest) Reset()         { *m = LockRequest{} }
func (m *LockRequest) String() string { return proto.CompactTextString(m) }
func (*LockRequest) ProtoMessage()    {}
func (*LockRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7e1fe3d4eec11dd6, []int{4}
}

func (m *LockRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LockRequest.Unmarshal(m, b)
}
func (m *LockRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LockRequest.Marshal(b, m, deterministic)
}
func (m *LockRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LockRequest.Merge(m, src)
}
func (m *LockRequest) XXX_Size() int {
	return xxx_messageInfo_LockRequest.Size(m)
}
func (m *LockRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LockRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LockRequest proto.InternalMessageInfo

func (m *LockRequest) GetAbsolutePath() string {
	if m != nil {
		return m.AbsolutePath
	}
	return ""
}

type LockResponse struct {
	AbsolutePath         string   `protobuf:"bytes,1,opt,name=AbsolutePath,proto3" json:"AbsolutePath,omitempty"`
	LockId               int64    `protobuf:"varint,2,opt,name=LockId,proto3" json:"LockId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LockResponse) Reset()         { *m = LockResponse{} }
func (m *LockResponse) String() string { return proto.CompactTextString(m) }
func (*LockResponse) ProtoMessage()    {}
func (*LockResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7e1fe3d4eec11dd6, []int{5}
}

func (m *LockResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LockResponse.Unmarshal(m, b)
}
func (m *LockResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LockResponse.Marshal(b, m, deterministic)
}
func (m *LockResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LockResponse.Merge(m, src)
}
func (m *LockResponse) XXX_Size() int {
	return xxx_messageInfo_LockResponse.Size(m)
}
func (m *LockResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LockResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LockResponse proto.InternalMessageInfo

func (m *LockResponse) GetAbsolutePath() string {
	if m != nil {
		return m.AbsolutePath
	}
	return ""
}

func (m *LockResponse) GetLockId() int64 {
	if m != nil {
		return m.LockId
	}
	return 0
}

type UnlockRequest struct {
	LockId               int64    `protobuf:"varint,1,opt,name=lockId,proto3" json:"lockId,omitempty"`
	AbsolutePath         string   `protobuf:"bytes,2,opt,name=AbsolutePath,proto3" json:"AbsolutePath,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UnlockRequest) Reset()         { *m = UnlockRequest{} }
func (m *UnlockRequest) String() string { return proto.CompactTextString(m) }
func (*UnlockRequest) ProtoMessage()    {}
func (*UnlockRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7e1fe3d4eec11dd6, []int{6}
}

func (m *UnlockRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UnlockRequest.Unmarshal(m, b)
}
func (m *UnlockRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UnlockRequest.Marshal(b, m, deterministic)
}
func (m *UnlockRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UnlockRequest.Merge(m, src)
}
func (m *UnlockRequest) XXX_Size() int {
	return xxx_messageInfo_UnlockRequest.Size(m)
}
func (m *UnlockRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UnlockRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UnlockRequest proto.InternalMessageInfo

func (m *UnlockRequest) GetLockId() int64 {
	if m != nil {
		return m.LockId
	}
	return 0
}

func (m *UnlockRequest) GetAbsolutePath() string {
	if m != nil {
		return m.AbsolutePath
	}
	return ""
}

type UnlockResponse struct {
	AbsolutePath         string   `protobuf:"bytes,1,opt,name=AbsolutePath,proto3" json:"AbsolutePath,omitempty"`
	LeaseId              int64    `protobuf:"varint,2,opt,name=LeaseId,proto3" json:"LeaseId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UnlockResponse) Reset()         { *m = UnlockResponse{} }
func (m *UnlockResponse) String() string { return proto.CompactTextString(m) }
func (*UnlockResponse) ProtoMessage()    {}
func (*UnlockResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7e1fe3d4eec11dd6, []int{7}
}

func (m *UnlockResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UnlockResponse.Unmarshal(m, b)
}
func (m *UnlockResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UnlockResponse.Marshal(b, m, deterministic)
}
func (m *UnlockResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UnlockResponse.Merge(m, src)
}
func (m *UnlockResponse) XXX_Size() int {
	return xxx_messageInfo_UnlockResponse.Size(m)
}
func (m *UnlockResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UnlockResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UnlockResponse proto.InternalMessageInfo

func (m *UnlockResponse) GetAbsolutePath() string {
	if m != nil {
		return m.AbsolutePath
	}
	return ""
}

func (m *UnlockResponse) GetLeaseId() int64 {
	if m != nil {
		return m.LeaseId
	}
	return 0
}

type Subscribe struct {
	Absolutepath         string   `protobuf:"bytes,1,opt,name=Absolutepath,proto3" json:"Absolutepath,omitempty"`
	Prefix               bool     `protobuf:"varint,2,opt,name=Prefix,proto3" json:"Prefix,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Subscribe) Reset()         { *m = Subscribe{} }
func (m *Subscribe) String() string { return proto.CompactTextString(m) }
func (*Subscribe) ProtoMessage()    {}
func (*Subscribe) Descriptor() ([]byte, []int) {
	return fileDescriptor_7e1fe3d4eec11dd6, []int{8}
}

func (m *Subscribe) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Subscribe.Unmarshal(m, b)
}
func (m *Subscribe) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Subscribe.Marshal(b, m, deterministic)
}
func (m *Subscribe) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Subscribe.Merge(m, src)
}
func (m *Subscribe) XXX_Size() int {
	return xxx_messageInfo_Subscribe.Size(m)
}
func (m *Subscribe) XXX_DiscardUnknown() {
	xxx_messageInfo_Subscribe.DiscardUnknown(m)
}

var xxx_messageInfo_Subscribe proto.InternalMessageInfo

func (m *Subscribe) GetAbsolutepath() string {
	if m != nil {
		return m.Absolutepath
	}
	return ""
}

func (m *Subscribe) GetPrefix() bool {
	if m != nil {
		return m.Prefix
	}
	return false
}

type StateChange struct {
	AbsolutePath         string   `protobuf:"bytes,1,opt,name=AbsolutePath,proto3" json:"AbsolutePath,omitempty"`
	EventType            int32    `protobuf:"varint,2,opt,name=EventType,proto3" json:"EventType,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StateChange) Reset()         { *m = StateChange{} }
func (m *StateChange) String() string { return proto.CompactTextString(m) }
func (*StateChange) ProtoMessage()    {}
func (*StateChange) Descriptor() ([]byte, []int) {
	return fileDescriptor_7e1fe3d4eec11dd6, []int{9}
}

func (m *StateChange) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StateChange.Unmarshal(m, b)
}
func (m *StateChange) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StateChange.Marshal(b, m, deterministic)
}
func (m *StateChange) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StateChange.Merge(m, src)
}
func (m *StateChange) XXX_Size() int {
	return xxx_messageInfo_StateChange.Size(m)
}
func (m *StateChange) XXX_DiscardUnknown() {
	xxx_messageInfo_StateChange.DiscardUnknown(m)
}

var xxx_messageInfo_StateChange proto.InternalMessageInfo

func (m *StateChange) GetAbsolutePath() string {
	if m != nil {
		return m.AbsolutePath
	}
	return ""
}

func (m *StateChange) GetEventType() int32 {
	if m != nil {
		return m.EventType
	}
	return 0
}

func init() {
	proto.RegisterEnum("transports.EventType", EventType_name, EventType_value)
	proto.RegisterType((*LeaseRequest)(nil), "transports.LeaseRequest")
	proto.RegisterType((*LeaseResponse)(nil), "transports.LeaseResponse")
	proto.RegisterType((*LeaseRelease)(nil), "transports.LeaseRelease")
	proto.RegisterType((*LeaseReleaseResponse)(nil), "transports.LeaseReleaseResponse")
	proto.RegisterType((*LockRequest)(nil), "transports.LockRequest")
	proto.RegisterType((*LockResponse)(nil), "transports.LockResponse")
	proto.RegisterType((*UnlockRequest)(nil), "transports.UnlockRequest")
	proto.RegisterType((*UnlockResponse)(nil), "transports.UnlockResponse")
	proto.RegisterType((*Subscribe)(nil), "transports.Subscribe")
	proto.RegisterType((*StateChange)(nil), "transports.StateChange")
}

func init() { proto.RegisterFile("whatnot.proto", fileDescriptor_7e1fe3d4eec11dd6) }

var fileDescriptor_7e1fe3d4eec11dd6 = []byte{
	// 469 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x54, 0xcd, 0x6e, 0xd3, 0x40,
	0x10, 0xc6, 0x4e, 0xeb, 0x26, 0x93, 0x04, 0x85, 0x15, 0x84, 0x10, 0x71, 0x88, 0x7c, 0x8a, 0x38,
	0x38, 0xa1, 0x3c, 0x41, 0x48, 0x57, 0xa8, 0xad, 0x45, 0x2b, 0x27, 0xe5, 0xc0, 0x6d, 0xed, 0x6c,
	0x1b, 0x0b, 0xe3, 0x35, 0xbb, 0xe3, 0x02, 0x4f, 0xc3, 0xab, 0x22, 0xdb, 0x1b, 0xff, 0x88, 0x44,
	0x22, 0xea, 0xc9, 0x9e, 0xbf, 0x6f, 0xbe, 0x6f, 0x76, 0x76, 0xa1, 0xff, 0x73, 0xcb, 0x30, 0x16,
	0xe8, 0x24, 0x52, 0xa0, 0x20, 0x80, 0x92, 0xc5, 0x2a, 0x11, 0x12, 0x95, 0x7d, 0x0f, 0x3d, 0x97,
	0x33, 0xc5, 0x3d, 0xfe, 0x23, 0xe5, 0x0a, 0x89, 0x0d, 0xbd, 0x85, 0xaf, 0x44, 0x94, 0x22, 0xbf,
	0x65, 0xb8, 0x1d, 0x19, 0x13, 0x63, 0xda, 0xf1, 0x1a, 0x3e, 0x32, 0x86, 0xf6, 0x45, 0x2a, 0x19,
	0x86, 0x22, 0x1e, 0x99, 0x13, 0x63, 0xda, 0xf2, 0x4a, 0x9b, 0x0c, 0xc1, 0xba, 0x95, 0xfc, 0x3e,
	0xfc, 0x35, 0x6a, 0x4d, 0x8c, 0x69, 0xdb, 0xd3, 0x96, 0x1d, 0x42, 0x5f, 0xf7, 0x51, 0x89, 0x88,
	0x15, 0x7f, 0x72, 0xa3, 0x11, 0x9c, 0xe5, 0x80, 0x97, 0x9b, 0xbc, 0x53, 0xcb, 0xdb, 0x99, 0xf6,
	0xb4, 0x94, 0x14, 0x65, 0x9f, 0x7a, 0xa6, 0xd1, 0xcc, 0x9c, 0xc3, 0xcb, 0x7a, 0x66, 0xc9, 0xed,
	0x70, 0xc5, 0x7b, 0xe8, 0xba, 0x22, 0xf8, 0x76, 0xc4, 0xb4, 0xec, 0x2b, 0xe8, 0x15, 0x25, 0x47,
	0x08, 0x1f, 0x82, 0x95, 0xd5, 0x5c, 0x6e, 0xb4, 0x6c, 0x6d, 0xd9, 0xd7, 0xd0, 0xbf, 0x8b, 0xa3,
	0x1a, 0x81, 0x21, 0x58, 0x51, 0x91, 0x58, 0x10, 0xd5, 0xd6, 0x3f, 0x4d, 0xcc, 0x3d, 0xc4, 0x3e,
	0xc3, 0xf3, 0x1d, 0xd8, 0x11, 0xd4, 0x6a, 0xb3, 0x31, 0x9b, 0xb3, 0xf9, 0x04, 0x9d, 0x55, 0xea,
	0xab, 0x40, 0x86, 0x7e, 0x03, 0x2a, 0xd9, 0x03, 0x95, 0x68, 0x95, 0x7a, 0x57, 0xcc, 0xc6, 0xae,
	0xdc, 0x40, 0x77, 0x85, 0x0c, 0xf9, 0x72, 0xcb, 0xe2, 0x87, 0xff, 0x63, 0xf5, 0x16, 0x3a, 0xf4,
	0x91, 0xc7, 0xb8, 0xfe, 0x9d, 0xf0, 0x1c, 0xed, 0xd4, 0xab, 0x1c, 0xef, 0x68, 0x2d, 0x4a, 0x3a,
	0x70, 0xea, 0xd2, 0xc5, 0x8a, 0x0e, 0x9e, 0x91, 0x36, 0x9c, 0xb8, 0x37, 0xcb, 0xeb, 0x81, 0x41,
	0xba, 0x70, 0xe6, 0xd1, 0xc2, 0x6d, 0x12, 0x00, 0x6b, 0xe9, 0xd1, 0xc5, 0x9a, 0x0e, 0x5a, 0xd9,
	0xff, 0x05, 0x75, 0xe9, 0x9a, 0x0e, 0x4e, 0xce, 0xbf, 0x40, 0x3f, 0xe3, 0x95, 0xaa, 0xbb, 0x64,
	0xc3, 0x90, 0x2b, 0x42, 0xe1, 0x45, 0xa9, 0x78, 0x2d, 0xf2, 0x16, 0x8a, 0xbc, 0x72, 0xaa, 0xeb,
	0xe5, 0x94, 0xe1, 0xf1, 0xeb, 0x86, 0xbb, 0x92, 0x37, 0x37, 0xce, 0xff, 0x18, 0x7a, 0x63, 0x57,
	0x5c, 0x3e, 0x86, 0x01, 0x27, 0x4b, 0xe8, 0xe9, 0x03, 0x76, 0x8b, 0x0d, 0xae, 0xd7, 0xd6, 0xaf,
	0xeb, 0xf8, 0xcd, 0x9e, 0x88, 0x3e, 0xcc, 0xab, 0x0c, 0x24, 0xdf, 0xeb, 0xc3, 0x20, 0x79, 0x78,
	0x3c, 0x39, 0x14, 0xd9, 0x61, 0x7d, 0x9c, 0x7f, 0x75, 0x1e, 0x42, 0xdc, 0xa6, 0xbe, 0x13, 0x88,
	0xef, 0xb3, 0x0d, 0x43, 0xe6, 0x73, 0xa6, 0x70, 0xa6, 0xdf, 0x95, 0x20, 0x4a, 0x15, 0x72, 0x39,
	0xab, 0x60, 0x7c, 0x2b, 0x7f, 0x6a, 0x3e, 0xfc, 0x0d, 0x00, 0x00, 0xff, 0xff, 0xd0, 0x5e, 0x4b,
	0x80, 0x7b, 0x04, 0x00, 0x00,
}
